import type { Product } from '../types'

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'mock-1',
    name: 'Aurore',
    description: 'O lucrare abstractă care captează lumina zorilor prin straturi de aur și bej. Textura puternică creează adâncime și mișcare, aducând căldură oricărui spațiu.',
    price: 1200,
    compare_price: 1500,
    show_compare_price: true,
    sku: 'SNA-001',
    stock_qty: 1,
    category: 'Abstract Gold',
    dimensions: '60x80 cm',
    technique: 'Acrilic + Foiță de Aur',
    surface: 'Pânză pe șasiu',
    images: [],
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-2',
    name: 'Liniște',
    description: 'Compoziție în tonuri neutre, cu texturi subtile și accente fine de aur. Transmite calm și eleganță discretă.',
    price: 950,
    compare_price: undefined,
    show_compare_price: false,
    sku: 'SNA-002',
    stock_qty: 1,
    category: 'Neutral Collection',
    dimensions: '50x70 cm',
    technique: 'Mixed Media',
    surface: 'Pânză înrămată',
    images: [],
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-3',
    name: 'Strat cu strat',
    description: 'Lucrare texturată în tehnica pasta relief, cu suprafețe bogate care invită atingerea. Un joc de lumini și umbre.',
    price: 1800,
    compare_price: undefined,
    show_compare_price: false,
    sku: 'SNA-003',
    stock_qty: 1,
    category: 'Textured Art',
    dimensions: '80x100 cm',
    technique: 'Pastă de Textură',
    surface: 'Pânză pe șasiu',
    images: [],
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-4',
    name: 'Ecuilibru',
    description: 'Piesă creată la comandă, cu dimensiuni și culori adaptate spațiului clientului. Fiecare lucrare personalizată este unică.',
    price: 2200,
    compare_price: undefined,
    show_compare_price: false,
    sku: 'SNA-004',
    stock_qty: 1,
    category: 'Custom Works',
    dimensions: '100x120 cm',
    technique: 'Acrilic + Foiță de Aur',
    surface: 'Pânză pe șasiu',
    images: [],
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-5',
    name: 'Fluiditate',
    description: 'Tehnica alcohol ink creează forme organice imprevizibile, cu accente metalice și tranziții de culoare unice.',
    price: 750,
    compare_price: undefined,
    show_compare_price: false,
    sku: 'SNA-005',
    stock_qty: 1,
    category: 'Abstract Gold',
    dimensions: '40x50 cm',
    technique: 'Alcohol Ink',
    surface: 'Pânză pe șasiu',
    images: [],
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-6',
    name: 'Terra',
    description: 'Inspirată de peisajele terestre văzute de sus. Tonuri de pământ, ocru și auriu se împletesc în relief.',
    price: 1400,
    compare_price: undefined,
    show_compare_price: false,
    sku: 'SNA-006',
    stock_qty: 2,
    category: 'Neutral Collection',
    dimensions: '70x100 cm',
    technique: 'Mixed Media',
    surface: 'Pânză pe șasiu',
    images: [],
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
